apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Mimir
      exemplarTraceIdDestinations:
        - name: traceId
          datasourceUid: "tempo"

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: "tempo"
          matcherRegex: "(?:traceId|trace_id|traceId:)\\s*=?\\s*([a-fA-F0-9]{32}|[a-fA-F0-9]{16})"
          name: TraceID
          url: "$${__value.raw}"

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: "loki"
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: "mimir"
      serviceMap:
        datasourceUid: "mimir"
      nodeGraph:
        enabled: true
